development: &DEVELOP
  bucket: "dev.tapes.fm"
  access_key_id: AKIAJLUDMFIAAGNUJOIQ
  secret_access_key: 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

production:
  bucket: "tapes.fm"
  access_key_id: AKIAJLUDMFIAAGNUJOIQ
  secret_access_key: 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

release:
  bucket: "tapes.fm"
  access_key_id: AKIAJLUDMFIAAGNUJOIQ
  secret_access_key: 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

test: *DEVELOP
