Tapedeck.create!(name: "Shila", description: "jojo das ein type", genre: "Rock")
Tapedeck.create!(name: "Haviana", description: "jojo das ein type", genre: "Rock")
Tapedeck.create!(name: "Kcena", description: "ddfdsfsd", genre: "Rock")
Tapedeck.create!(name: "Mirta", description: "fgf44 fdfds", genre: "Rock")
Tapedeck.create!(name: "Olivia", description: "jojo das ein type", genre: "Rock")
Tapedeck.create!(name: "Hillery", description: "jojo das ein type", genre: "Rock")
Tapedeck.create!(name: "Hallona", description: " fdfds", genre: "Rock")
