Tape.create!(name: "Shila", bpm: "122")
Tape.create!(name: "Kcena", bpm: "130")
Tape.create!(name: "Olivia", bpm: "152")
Tape.create!(name: "Heaviana", bpm: "152")
Tape.create!(name: "Mountain", bpm: "100")
