---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-3265305a
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_app
  - tapesfm_production_app01
  - tapesfm_production_unicorn
  - tapesfm_production_nginx
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-54-235-183-203.compute-1.amazonaws.com
  external_ip: 54.235.183.203
  internal_host: ip-10-72-254-198.ec2.internal
  internal_ip: 10.72.254.198
  zone: us-east-1d
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: resque01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-52b7bc31
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_resque01
  - tapesfm_production_resque_worker
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-54-235-35-39.compute-1.amazonaws.com
  external_ip: 54.235.35.39
  internal_host: ip-10-140-70-208.ec2.internal
  internal_ip: 10.140.70.208
  zone: us-east-1d
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
