---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-b607bdc6
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_app
  - tapesfm_production_app01
  - tapesfm_production_unicorn
  - tapesfm_production_nginx
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-54-235-183-203.compute-1.amazonaws.com
  external_ip: 54.235.183.203
  internal_host: domU-12-31-39-0A-3E-16.compute-1.internal
  internal_ip: 10.211.61.224
  zone: us-east-1d
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: resque01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-6e189d1e
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_resque01
  - tapesfm_production_resque_worker
  - tapesfm_production_db
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-184-73-73-8.compute-1.amazonaws.com
  external_ip: 184.73.73.8
  internal_host: ip-10-244-142-213.ec2.internal
  internal_ip: 10.244.142.213
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
