---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: mongodb01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-ce6004b4
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_mongodb01
  - tapesfm_production_mongodb
  - tapesfm_production_db
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-107-20-51-61.compute-1.amazonaws.com
  external_ip: 107.20.51.61
  internal_host: ip-10-245-130-7.ec2.internal
  internal_ip: 10.245.130.7
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-2e630754
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_app01
  - tapesfm_production_app
  - tapesfm_production_passenger_nginx
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-75-101-222-5.compute-1.amazonaws.com
  external_ip: 75.101.222.5
  internal_host: ip-10-10-45-136.ec2.internal
  internal_ip: 10.10.45.136
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-626e0a18
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - tapesfm_production_default
  - tapesfm_production_web
  - tapesfm_production_web01
  - tapesfm_production_haproxy
  - tapesfm_production_collectd
  - tapesfm_production_monit
  external_host: ec2-50-16-178-227.compute-1.amazonaws.com
  external_ip: 50.16.178.227
  internal_host: ip-10-60-158-238.ec2.internal
  internal_ip: 10.60.158.238
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
